### ISSUE TITLE
URLs aren't validated

### ISSUE THREAD

**Issue by aubergene** [PeoplesMomentum/momentum-voter-reg#3]
No validation on urls means some don't start with http and therefore are considered relative urls
http://democracy-sos.peoplesmomentum.com/events/7
links to
http://democracy-sos.peoplesmomentum.com/events/www.facebook.com/events/565809330233252/

**Comment by james** [comment]
Yes, there is no validation at all at the moment. It's on my to do list. Will also have to make error pages for it...
